//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "keycloak", table_name = "user_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub email: Option<String>,
    pub email_constraint: Option<String>,
    pub email_verified: bool,
    pub enabled: bool,
    pub federation_link: Option<String>,
    pub first_name: Option<String>,
    pub last_name: Option<String>,
    pub realm_id: Option<String>,
    pub username: Option<String>,
    pub created_timestamp: Option<i64>,
    pub service_account_client_link: Option<String>,
    pub not_before: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
